services:
  drupal:
    image: drupal:10-apache
    container_name: drupal
    restart: always
    ports:
      - "8081:80"  # Exponemos el puerto 8081 del host al 80 del contenedor
    volumes:
      - ./web:/var/www/html
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
